[package]
name = "cgp-example-profile-picture"
version = "0.1.0"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }

[dependencies]
cgp             = { workspace = true }

anyhow          = { version = "1" }
sqlx            = { version = "0.8.6", features = ["postgres"] }
aws-sdk-s3      = { version = "1.127.0" }
image           = { version = "0.25.10" }
