[package]
name = "cgp-example-transfer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "bin/server.rs"

[dependencies]
cgp                 = { version = "0.3.0", features = ["provider-supertrait"] }
anyhow              = { version = "1.0.95" }
futures             = { version = "0.3.31" }
num-traits          = { version = "0.2.19" }
serde               = { version = "1.0.217", features = ["derive"]}
axum                = { version = "0.8.1" }
axum-extra          = { version = "0.10.0", features = ["typed-header"]}
headers             = { version = "0.4.0" }
tokio               = { version = "1.43.0", features = ["full"] }

[patch.crates-io]
cgp                         = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-core                    = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-extra                   = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-async                   = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-async-macro             = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-component               = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-component-macro         = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-component-macro-lib     = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-type                    = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-field                   = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-field-macro             = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-field-macro-lib         = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-error                   = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-error-extra             = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-error-anyhow            = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-run                     = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-runtime                 = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-sync                    = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
cgp-inner                   = { git = "https://github.com/contextgeneric/cgp.git", branch = "cgp-type-redesign" }
