[package]
name = "cgp-example-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
cgp                 = { version = "0.4.1" }
cgp-error-anyhow    = { version = "0.4.1" }
sqlx                = { version = "0.8.6", features = ["sqlite"] }
rig-core            = { version = "0.13.0" }