[package]
name = "cgp-example-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
cgp                 = { version = "0.4.1" }
rusqlite            = { version = "0.36.0" }
rig-core            = { version = "0.13.0" }